#include "../H/symbols.h"

const char *const SYMBOLS[] = {
    [MENU_TOP_LEFT] = "\u250F",
    [MENU_TOP] = "\u2501",
    [MENU_TOP_RIGHT] = "\u2513",
    [MENU_LEFT] = "\u2503",
    [MENU_RIGHT] = "\u2503",
    [MENU_BOTTOM_LEFT] = "\u2517",
    [MENU_BOTTOM_RIGHT] = "\u251B",
    [MENU_BOTTOM] = "\u2501",
    [MENU_SEPARATOR_LEFT] = "\u2520",
    [MENU_SEPARATOR_RIGHT] = "\u2528",
    [MENU_SEPARATOP_CROSS] = "\u254B",
    [MENU_SEPARATOR_HORIZONTAL] = "\u2500",
    [MENU_SEPARATOR_VERITCAL] = "\u2503",
    [MENU_UNSELECTED] = " ",
    [MENU_SELECTED] = "\u2981",
    [TEXT_TO_LONG] = "\u2026",
    [INFOSCREEN_TOP_LEFT] = "\u2554",
    [INFOSCREEN_TOP] = "\u2550",
    [INFOSCREEN_TOP_RIGHT] = "\u2557",
    [INFOSCREEN_LEFT] = "\u2551",
    [INFOSCREEN_RIGHT] = "\u2551",
    [INFOSCREEN_BOTTOM_LEFT] = "\u255A",
    [INFOSCREEN_BOTTOM] = "\u2550",
    [INFOSCREEN_BOTTOM_RIGHT] = "\u255D",
    [MENU_ACTION] = "\u27A5"
};