#ifndef SYMBOLS_H
#define SYMBOLS_H

typedef enum {
    MENU_TOP_LEFT,
    MENU_TOP,
    MENU_TOP_RIGHT,
    MENU_LEFT,
    MENU_RIGHT,
    MENU_BOTTOM,
    MENU_BOTTOM_LEFT,
    MENU_BOTTOM_RIGHT,
    MENU_SEPARATOR_LEFT,
    MENU_SEPARATOR_RIGHT,
    MENU_SEPARATOR_TOP,
    MENU_SEPARATOR_BOTTOM,
    MENU_SEPARATOP_CROSS,
    MENU_SEPARATOR_HORIZONTAL,
    MENU_SEPARATOR_VERITCAL,
    MENU_UNSELECTED,
    MENU_SELECTED,
    MENU_ACTION,
    TEXT_TO_LONG,
    INFOSCREEN_TOP_LEFT,
    INFOSCREEN_TOP,
    INFOSCREEN_TOP_RIGHT,
    INFOSCREEN_LEFT,
    INFOSCREEN_RIGHT,
    INFOSCREEN_BOTTOM_LEFT,
    INFOSCREEN_BOTTOM,
    INFOSCREEN_BOTTOM_RIGHT,
    SYMBOL_COUNT
} SYMBOLID;

extern const char *const SYMBOLS[SYMBOL_COUNT];

#endif