#ifndef SYMBOLS_H
#define SYMBOLS_H

typedef enum {
    MENU_TOP_LEFT,
    MENU_TOP,
    MENU_TOP_RIGHT,
    MENU_LEFT,
    MENU_RIGHT,
    MENU_BOTTOM,
    MENU_BOTTOM_LEFT,
    MENU_BOTTOM_RIGHT,
    MENU_SEPARATOR_LEFT,
    MENU_SEPARATOR_RIGHT,
    MENU_SEPARATOR_TOP,
    MENU_SEPARATOR_BOTTOM,
    MENU_SEPARATOP_CROSS,
    MENU_SEPARATOR_HORIZONTAL,
    MENU_SEPARATOR_VERITCAL,
    MENU_SELECTED,
    TEXT_TO_LONG,
    INFOLINE_TOP_LEFT,
    INFOLINE_TOP,
    INFOLINE_TOP_RIGHT,
    INFOLINE_LEFT,
    INFOLINE_RIGHT,
    INFOLINE_BOTTOM_LEFT,
    INFOLINE_BOTTOM,
    INFOLINE_BOTTOM_RIGHT
} SymbolIndex;

const char *SYMBOLS[] = {
    [MENU_TOP_LEFT] = "\u250F",
    [MENU_TOP] = "\u2501",
    [MENU_TOP_RIGHT] = "\u2513",
    [MENU_LEFT] = "\u2503",
    [MENU_RIGHT] = "\u2503",
    [MENU_BOTTOM_LEFT] = "\u2517",
    [MENU_BOTTOM_RIGHT] = "\u251B",
    [MENU_BOTTOM] = "\u2501",
    [MENU_SEPARATOR_LEFT] = "\u2520",
    [MENU_SEPARATOR_RIGHT] = "\u2528",
    [MENU_SEPARATOP_CROSS] = "\u254B",
    [MENU_SEPARATOR_HORIZONTAL] = "\u2500",
    [MENU_SEPARATOR_VERITCAL] = "\u2503",
    [MENU_SELECTED] = "\u2981",
    [TEXT_TO_LONG] = "\u2026",
    [INFOLINE_TOP_LEFT] = "\u2554",
    [INFOLINE_TOP] = "\u2550",
    [INFOLINE_TOP_RIGHT] = "\u2557",
    [INFOLINE_LEFT] = "\u2551",
    [INFOLINE_RIGHT] = "\u2551",
    [INFOLINE_BOTTOM_LEFT] = "\u255A",
    [INFOLINE_BOTTOM] = "\u2550",
    [INFOLINE_BOTTOM_RIGHT] = "\u255D"
};

#endif